[package]
name = "eframe-fit-content"
version = "0.1.0"
edition = "2024"
authors = ["PJaros <jaros.paul@gmail.com>"]
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
eframe = "0.33.0"

[profile.release]
#opt-level = "z"
opt-level = "s"
lto = true
strip = "symbols"
